name: todo
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  intl: ^0.18.1
  supabase_flutter: ^1.10.4
  flutter_dotenv: ^5.1.0
  adaptive_theme: ^3.3.0
  auto_route: ^7.5.0
  flutter_form_validators:
    git: https://github.com/saurav64bit/flutter_form_validators

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - .env
    - assets/

